Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -145,37 +145,26 @@ jobs:
           else
             CONFIG=${{ matrix.name }}/out/.config
           fi
-          grep -q "CONFIG_KSU=y" "$CONFIG" && echo "✅ CONFIG_SUKi found!" || echo "❌ CONFIG_KSU not found!"
-          grep -q "CONFIG_KSU_SUSFS=y" "$CONFIG" && echo "✅ CONFIG_SUKI_SUSFS found!" || echo "❌ CONFIG_KSU_SUSFS not found!"
+          grep -q "CONFIG_KSU=y" "$CONFIG" && echo "✅ CONFIG_KSU found!" || echo "❌ CONFIG_KSU not found!"
+          grep -q "CONFIG_KSU_SUSFS=y" "$CONFIG" && echo "✅ CONFIG_KSU_SUSFS found!" || echo "❌ CONFIG_KSU_SUSFS not found!"
           grep -q "CONFIG_SECURITYFS=y" "$CONFIG" && echo "✅ CONFIG_SECURITYFS found!" || echo "❌ CONFIG_SECURITYFS not found!"
       
-      - name: Package Kernel with AnyKernel3
-        id: zipkernel
-        run: |
-          DATE=$(date +%Y%m%d)
-          echo "DATE=$DATE" >> $GITHUB_ENV
-          if [[ "${{ matrix.name }}" == "noroot" ]]; then
-            ZIP_NAME="TegarXLu-GKI-${DATE}.zip"
-            OUT_DIR="kernel"
-          elif [[ "${{ matrix.name }}" == "ksunext" ]]; then
-            ZIP_NAME="TegarXLu-GKI-KSUNext+SUSFS-${DATE}.zip"
-            OUT_DIR="ksunext"
-          elif [[ "${{ matrix.name }}" == "sukisu" ]]; then
-            ZIP_NAME="TegarXLu-GKI-SukiSU+SUSFS-${DATE}.zip"
-            OUT_DIR="sukisu"
-          fi
-          git clone https://github.com/TegarXLu/AnyKernel3-Templar-SukiSu
-          cp $OUT_DIR/out/arch/arm64/boot/Image AnyKernel3/
-          cd AnyKernel3
-          zip -r9 "../$ZIP_NAME" ./*
-          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT
-      
-      - name: Upload Artifact
+      - name: Upload Artifact (AK3 and Images)
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ steps.zipkernel.outputs.zip_name }}
-          path: ${{ steps.zipkernel.outputs.zip_name }}
-
+          name: ${{ env.BASE_NAME }}-${{ github.run_number }}
+          retention-days: 1
+          path: |
+            artifacts/*.zip
+            artifacts/*.img
+      - name: Upload Artifact (Info file)
+        if: ${{ env.STATUS }} == 'RELEASE'
+        uses: actions/upload-artifact@v4
+        with:
+          name: info-${{ github.run_number }}
+          retention-days: 1
+          path: |
+            artifacts/*.txt
   finalize:
     needs: [set-date, build]
     runs-on: ubuntu-latest
@@ -194,7 +183,6 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           path: .
-
       - name: Generate Release Notes
         run: |
           echo "🔧 **TegarXLu GKI Release**" > release.txt
